
site:
  name: UNIMEDIA
  title: UNIMEDIA - Portalul de știri nr. 1 din Moldova
  host: unimedia.info

defaultSection: pages

assets:
  names:
    css_main:
      - static/css/normalize.css
      - static/css/bootstrap.css
      - static/css/main.css