
site:
  name: UNIMEDIA
  title: UNIMEDIA - Portalul de știri nr. 1 din Moldova
  host: unimedia.info

defaultSection: pages

###  VARIABLES
# name - document name
# slug - document slug
# title - slug, name
# section - document section
# type - document type
### group_GROUPNAME - example: group_tags or group_categories
# year - document 4 year
# month - 01..12
# i_month - 1..12
# day - 01..31
# i_day - 1..31
# short_year - 2014 > 14
# extension - file extension
###
permalink:
  simple: :section/:title.:extension


assets:
  names:
    css-main:
      - static/css/normalize.css
      - static/css/bootstrap.css
      - static/css/main.css