
dynamics:
  - source:
      da: news.categories
    document:
      layout: category
      #what property of category will become document.title
      title: name
      #permalink
      permalink: /:slug/index.html
      extensions: ['html','ejs']