
generators:
  category:
    type: item
    source:
      da: news.categories
      params:
        limit: 8
      limit: 0
    output:
      layout: category

  latestnews:
    type: list
    source:
      da: news.latestNews
      params:
        limit: 8
      limit: 1
    output:
      layout: category