
tasks:
  ###############
  ## tags
  ###############

  # new tags, trigger when a document is published
  tags.new:
    task:
      type: list
      limit: 1
      source:
        storage: groups.freshTags
        params:
          time: '@{$10m}'
          limit: 20
      action:
        file:
          view: _layouts/tag.jade
    trigger: [document.published, document.unpublished]

  # fresh tags, trigger on every 3 hours
  tags.fresh:
    task:
      type: list
      source:
        storage: groups.freshTags
        params:
          time: '@{$6h}'
          limit: 20
      action:
        file:
          view: _layouts/tag.jade
    trigger: 3h

  # fresh categories, trigger on every 3 hours
  categories.fresh:
    task:
      type: list
      source:
        storage: groups.freshCategories
        params:
          time: '@{$6h}'
          limit: 20
      action:
        file:
          view: _layouts/category.jade
    trigger: [3h, document.published, document.unpublished]

  # # jsonpages categories, trigger on every 3 hours
  # categories.jsonpages:
  #   task:
  #     type: list
  #     limit: 1
  #     source:
  #       storage: groups.freshCategories
  #       params:
  #         time: '@{$6h}'
  #         limit: 20
  #     action:
  #       task: news.pagesbycategory
  #       params:
  #         - [uniqueName, uniqueName]

  #   trigger: 3h

  #################
  # NEWS
  #################

  # new news, trigger when a document is published
  news.rss:
    task:
      type: page
      limit: 1
      source:
        storage: news.latest
        params:
          limit: 10
      action:
        file:
          view: _layouts/rss.xml.jade
    trigger: [document.published, document.unpublished]

  # # pages by category, trigger on demand
  # news.pagesbycategory:
  #   task:
  #     type: page
  #     limit: 10
  #     source:
  #       storage: news.latestByGroupItem
  #       params:
  #         limit: 10
  #     action:
  #       file:
  #         layout: news_group_page
  #   trigger: ondemand

  # fresh updated news, trigger on every 1h
  # news.fresh:
  #   task:
  #     type: list
  #     limit: 10
  #     source:
  #       storage: news.fresh
  #       params:
  #         time: '@{$65m}'
  #         limit: 10
  #     action:
  #       file:
  #         layout: news_item
  #   trigger: [30m, document.unpublished]

  # news.latest1h:
  #   task:
  #     type: list
  #     limit: 1
  #     source:
  #       storage: news.latestRange
  #       params:
  #         min: '@{$1h}'
  #         limit: 10
  #     action:
  #       file:
  #         layout: news_item
  #   trigger: [30m, document.published]


